---
driver:
  name: vagrant
  customize:
    memory: 5120
    cpus: 4


provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[variant-call::default]
    attributes:
